"""
Reusable KPI and presentation cards for LOANWISE AI.
"""

import streamlit as st


def render_kpi_card(label: str, value: str, subtext: str = "", border_color: str = "#E2E8F0"):
    """
    Renders an elevated KPI metric tile.
    """
    html = f"""
    <div class="kpi-card" style="border-left: 4px solid {border_color};">
        <div class="kpi-label">{label}</div>
        <div class="kpi-value">{value}</div>
        {f'<div class="kpi-subtext">{subtext}</div>' if subtext else ''}
    </div>
    """
    st.markdown(html, unsafe_allow_html=True)


def render_decision_banner(approved: bool, prob: float, model_name: str):
    """
    Renders the hero loan approval decision card.
    """
    pct = prob * 100
    if approved:
        html = f"""
        <div class="decision-card-approved">
            <h3>✓ LOAN LIKELY TO BE APPROVED</h3>
            <div style="font-size: 1.1rem; opacity: 0.95; margin-bottom: 6px;">
                Confidence: <b>{pct:.1f}%</b> Approval Probability
            </div>
            <div style="font-size: 0.85rem; opacity: 0.85;">
                Decision generated by <b>{model_name}</b> pipeline
            </div>
        </div>
        """
    else:
        html = f"""
        <div class="decision-card-rejected">
            <h3>✕ LOAN LIKELY TO BE REJECTED</h3>
            <div style="font-size: 1.1rem; opacity: 0.95; margin-bottom: 6px;">
                Confidence: <b>{(100 - pct):.1f}%</b> Rejection Probability
            </div>
            <div style="font-size: 0.85rem; opacity: 0.85;">
                Decision generated by <b>{model_name}</b> pipeline
            </div>
        </div>
        """
    st.markdown(html, unsafe_allow_html=True)


def render_risk_badge(risk_level: str):
    """
    Renders a color-coded risk assessment badge.
    """
    if "Low" in risk_level:
        badge_class = "badge-low-risk"
        icon = "🟢"
    elif "Mod" in risk_level:
        badge_class = "badge-mod-risk"
        icon = "🟡"
    else:
        badge_class = "badge-high-risk"
        icon = "🔴"

    html = f'<span class="badge {badge_class}">{icon} {risk_level}</span>'
    return html


def render_takeaway(text: str, title: str = "Observation"):
    """
    Renders a styled analytical takeaway callout box.
    """
    html = f"""
    <div class="takeaway-box">
        <strong>💡 {title}:</strong> {text}
    </div>
    """
    st.markdown(html, unsafe_allow_html=True)
